# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a611da4deabca57a250388144f6dd90d305e929b5ae10a7e5cf328e69dae2d46f28829f465ec6479ea364a4fee485a18684aee892f129b54bbb5066e96e7307

test:
  secret_key_base: 22d59c3192c384ad5910125cb77bb5d1ba3aa618ccf8dd5e7dff162ae68ac1e3c9b04d1f8adbabff68c9af99edcf9981912a7768242d1480ee43f3a9e623cb46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
